### ISSUE TITLE
Отрывается несколько окон Настройки после кликов на кнопку Настроить вид в окне регистрации 

### ISSUE THREAD

**Issue by Myndrila** [Students-of-the-city-of-Kostroma/tournament-project#118]
**Describe the bug**
Отрывается несколько окон Настройки после кликов на кнопку Настроить вид в окне регистрации 

**To Reproduce**
1. Перейти к окну регистрации
2. Несколько раз кликнуть на кнопку _Настроить вид_ 

**Expected result**
Отрывается несколько окон _Настройки_ после кликов на кнопку _Настроить вид_ в окне регистрации 
**Actual result**
Открывается только одно окно _Настройки_ || Блокировка окна/кнопки как только открывается окно _Настройки_ 
**Screenshots**
![окна](https://user-images.githubusercontent.com/81418253/153760802-82e32fdc-3416-48fb-8d97-bd8a5f341463.jpg)

**Comment by YuriSilenok** [comment]
@MariaMakii давайте введем что если ваш падован сделал задачу, он ее перевешивает на вас, а когда вы выпускаете релиз, тогда вы указываете в какой версии исправлен этот баг и вешаете на тестера.

**Comment by MariaMakii** [comment]
> @MariaMakii давайте введем что если ваш падован сделал задачу, он ее перевешивает на вас, а когда вы выпускаете релиз, тогда вы указываете в какой версии исправлен этот баг и вешаете на тестера.

Хорошо, поняла

**Comment by YuriSilenok** [comment]
> > @MariaMakii давайте введем что если ваш падован сделал задачу, он ее перевешивает на вас, а когда вы выпускаете релиз, тогда вы указываете в какой версии исправлен этот баг и вешаете на тестера.
> 
> Хорошо, поняла

Эта задача вошла в како-то релиз?

**Comment by Myndrila** [comment]
Баг не воспроизводится в [v0.8](https://github.com/Students-of-the-city-of-Kostroma/tournament-project/releases/tag/v0.8)
