### ISSUE TITLE
Подгрузка данных из бд для окна "Турнирная сетка"

### ISSUE THREAD

**Issue by AndreyMaraj** [Students-of-the-city-of-Kostroma/tournament-project#121]
Подгрузка данных из бд для окна "Турнирная сетка": группы, подгруппы, бойцы.

**Comment by AndreyMaraj** [comment]
Блокирующие задачи: 

- [ ] #120

**Comment by YuriSilenok** [comment]
> 

Почему это блокирующая задача? Отсутствие данных в БД как-то вас блокирует, разве вы не можете добавить данные в БД руками и на этих тестовых данных вести разработку?
