### ISSUE TITLE
Открытие окна "Протокол боя"

### ISSUE THREAD

**Issue by AndreyMaraj** [Students-of-the-city-of-Kostroma/tournament-project#122]
Открытие окна "Протокол боя" через кнопку "+" и передача в это окно данных о бое и о бойцах.

---
Блокирующие задачи:

- [x] #121

**Comment by AndreyMaraj** [comment]
Блокирующие задачи:

- [ ] #121

**Comment by YuriSilenok** [comment]
> Блокирующие задачи:
> 
> * [ ]  [Подгрузка данных из бд для окна "Турнирная сетка" #121](https://github.com/Students-of-the-city-of-Kostroma/tournament-project/issues/121)

эту информацию нужно дублировать в описание задачи
