### ISSUE TITLE
Принимаются проставленные пробелы в полях в окне регистрации судей

### ISSUE THREAD

**Issue by Myndrila** [Students-of-the-city-of-Kostroma/tournament-project#139]
**Describe the bug**
Принимаются проставленные пробелы в полях(ФИО, Город, Клуб) в окне регистрации судей 

**To Reproduce**
1. Проставить пробелы в полях регистрации судей
2. Кликнуть на кнопку _Сохранить_ 

**Expected result**
Не принимаются проставленные пробелы в полях(ФИО, Город, Клуб) в окне регистрации судей 
**Actual result**
Принимаются проставленные пробелы в полях(ФИО, Город, Клуб) в окне регистрации судей

**Comment by YuriSilenok** [comment]
@MariaMakii почему вы убрали метку [v0.7](https://github.com/Students-of-the-city-of-Kostroma/tournament-project/labels/v0.7)

**Comment by Myndrila** [comment]
Баг не воспроизводится в [v0.9](https://github.com/Students-of-the-city-of-Kostroma/tournament-project/releases/tag/v0.9)
