### ISSUE TITLE
Запись в БД статистики подгруппы

### ISSUE THREAD

**Issue by MariaMakii** [Students-of-the-city-of-Kostroma/tournament-project#152]
Блокирующие задачи: 

- [ ] #150

**Comment by MariaMakii** [comment]
Блокирующая задача #150

**Comment by YuriSilenok** [comment]
Что значит запись статистики в БД, статистика строиться по имеющимся данным, вы не должны хранить табличку со статистикой, вы должны сделать SQL запрос, который покажет вам данные в нужном виде для пользователя!

**Comment by YuriSilenok** [comment]
Задача была поднята ошибочно
