### ISSUE TITLE
Чтение из БД статистики подгруппы

### ISSUE THREAD

**Issue by MariaMakii** [Students-of-the-city-of-Kostroma/tournament-project#153]
Блокирующие задачи:

- [ ] #150

**Comment by MariaMakii** [comment]
Блокирующая задача #150

**Comment by YuriSilenok** [comment]
То, что написал о блокирующей задаче в комментариях, это хорошо. 
В описание задачи так же нужно формировать такой список. Сейчас покажу, далее вы сами.

**Comment by YuriSilenok** [comment]
Задача была поднята ошибочно
