### ISSUE TITLE
Загрузка боев в рамках фазы

### ISSUE THREAD

**Issue by AndreyMaraj** [Students-of-the-city-of-Kostroma/tournament-project#166]
Реализовать добавление информации о распределении участников подгруппы по боям в рамках фазы.
Сохранение в БД таблиц: Фаза, Протокол боя.

**Comment by YuriSilenok** [comment]
@MariaMakii метка backlog ставиться для всех задач и убирается тогда, когда вы переносите задачу на какой-то спринт.
Сейчас задача на какой-то спринт запланирована?
Еще, обратите внимание что описание задачи совпадает с заголовком. То есть, нет описания нет, непонятно что будет сделано. Какие таблицы это затронет, непонятно какие модели будут созданы, какие контроллеры будут созданы. 
А еще непонятно в рамках какого EPIC эта задача выполняется?

**Comment by AndreyMaraj** [comment]
> заголовком

Исправлено

**Comment by YuriSilenok** [comment]
Существуют ли сейчас классы модели для таблиц Фаза и Протокол боя?

**Comment by AndreyMaraj** [comment]
> 

да
