### ISSUE TITLE
Хранение данных в БД

### ISSUE THREAD

**Issue by AndreyMaraj** [Students-of-the-city-of-Kostroma/tournament-project#18]
Приложение должно иметь возможность добавлять и выборать данные из следующих таблиц:
  - [x] турнирная сетка
  - [x] номинация
  - [x] категория
  - [x] группа
  - [x] подгруппа
  - [x] участник
  - [x] клуб

**Comment by YuriSilenok** [comment]
нужно добавить описание, не совсем понятно что значит подключение БД.

**Comment by YuriSilenok** [comment]
когда изменения для этой задачи будут замержены в ветку дев, нужно выкатить релиз v0.4

**Comment by AndreyMaraj** [comment]
Добавлено сохранение в базу данных таблиц: Группа, Подгруппа.
