### ISSUE TITLE
Добавление предыдущих номинаций к новым в формировании групп после загрузки файла 

### ISSUE THREAD

**Issue by Myndrila** [Students-of-the-city-of-Kostroma/tournament-project#19]
**Describe the bug**
Добавление старых номинации к новым в формировании групп после загрузки файла 

**To Reproduce**
1. Зарегистрировать участников и перейти к формированию групп
2. Вернуться к регистрации 
3. Загрузить файл 
4. Перейти к формированию групп

**Expected result**
Отображение только номинаций из файла

**Actual result**
Отображение предыдущих номинации с новыми из файла

**Comment by YuriSilenok** [comment]
Исправления для бага в версии v0.3.2

**Comment by Myndrila** [comment]
Баг пофикшен
