### ISSUE TITLE
Участники распределяются с дубликатами и в неверном соотношении по подгруппам при правиле города; правиле города с посевными бойцами в формировании групп

### ISSUE THREAD

**Issue by Myndrila** [Students-of-the-city-of-Kostroma/tournament-project#21]
**Describe the bug**
Участники распределяются с дубликатом (участников) и в неверном количестве по подгруппам при правиле города; правиле города с посевными бойцами в формировании групп

**To Reproduce**
1. Загрузить 
[TestTable1.xlsx](https://github.com/Students-of-the-city-of-Kostroma/tournament-project/files/7777563/TestTable1.xlsx)
2. Перейти к формированию групп 
3. Выбрать правило города / правило города с посевными бойцами

**Expected result**
Формирование подгрупп без дубликата участников и в верном соотношении количества бойцов с количеством подгрупп при правиле города; правиле города с посевными бойцами : (13 бойцов на 5 подгрупп разделится на 5 подгрупп с количеством участников: 2; 2; 3; 3; 3) 

**Actual result**
Формирование подгрупп с дубликатом участников и с противоречивым соотношением количества бойцов с количеством подгрупп при правиле города; правиле города с посевными бойцами : (13 бойцов на 5 подгрупп разделяется на 5 подгрупп с количеством участников: 11; 11; 11; 11; 11) 

**Screenshots**
![baggorod](https://user-images.githubusercontent.com/81418253/147420004-9bbc8a48-b9d8-4c02-baef-f79a96e2fa84.jpg)

**Comment by YuriSilenok** [comment]
А разве этот баг не дублирует #22?

**Comment by YuriSilenok** [comment]
@MariaMakii вы должны здесь отписать тестировщику в какой версии он должен проверить что баг исправлен

**Comment by YuriSilenok** [comment]
и перевесить на тестировщика этот баг, который и так почему-то висит на тестировщике

**Comment by MariaMakii** [comment]
@Myndrila Баг исправлен в версии [v0.3.3](https://github.com/Students-of-the-city-of-Kostroma/tournament-project/releases/tag/v0.3.3)

**Comment by MariaMakii** [comment]
@Myndrila Исправлено в версии [v0.4](https://github.com/Students-of-the-city-of-Kostroma/tournament-project/releases/tag/v0.4)

**Comment by Myndrila** [comment]
Баг не воспроизводится в [v0.4](https://github.com/Students-of-the-city-of-Kostroma/tournament-project/releases/tag/v0.4)
