### ISSUE TITLE
Участники не распределяются по подгруппам по правилам города и посевных бойцов в формировании групп

### ISSUE THREAD

**Issue by Myndrila** [Students-of-the-city-of-Kostroma/tournament-project#22]
**Describe the bug**
Участники не распределяются по подгруппам по правилам города и посевных бойцов в формировании групп

**To Reproduce**
1. Загрузить 
[TestTable1.xlsx](https://github.com/Students-of-the-city-of-Kostroma/tournament-project/files/7777579/TestTable1.xlsx)
2. Перейти к формированию групп
3. Выбрать правило города и посевных бойцов

**Expected result**
Распределение участников по правилам города и посевных бойцов

**Actual result**
Участники не распределяются по правилам города и посевных бойцов

**Screenshots**
![pravilogoroda posevn](https://user-images.githubusercontent.com/81418253/147420156-47ff8ac8-81e2-4d35-a944-c3d78897ae1c.jpg)

**Comment by YuriSilenok** [comment]
Не могу понять, почему это баг? Что противоречит из представленных данных?
А исходя из названия бага, так это целых два бага. по багу на каждое правило.

**Comment by Myndrila** [comment]
1. Это баг потому что участники даже просто не делятся на подгруппы (12 бойцов запрос разбить на 6 подгрупп 12:6= по 2 человека в каждой подгруппе). Так же на скрине ниже можно увидеть, что участники дублируются.
![баг](https://user-images.githubusercontent.com/81418253/147506450-d473e136-56c3-48d1-984a-7b379e969fca.jpg)

2. Нет, это один баг. Правило города, города/посевных, города/одноклубников, города/посевных/одноклубников тестировалось отдельно. Подобный баг с неверным распределением/разбиением участников был выявлен только у правил города, города/посевных.

**Comment by YuriSilenok** [comment]
Тогда это все равно один баг, но уже по другой причине. Есть некоторая фнукция, которая распределяет участников по подгруппам и эта функция работает не правильно в определнных условиях, в баге и нужно будет перечислить при каких условиях работает не верно, а так же указать при каких условиях все работает хорошо. Возможно стоит представить таблицу.

**Comment by YuriSilenok** [comment]
Кроме этого, про количествол человек в группе и их дублирование в баг-репорте ничего не указано, не стоит в ожидаемом и файтичесом результате ссылаться на приваильную и неправильную работу, нужно описывать конкретно, что не так.

**Comment by Myndrila** [comment]
объединён с багом #21
