### ISSUE TITLE
Рефакторинг верстки окна регистрации

### ISSUE THREAD

**Issue by MariaMakii** [Students-of-the-city-of-Kostroma/tournament-project#26]
Чистка кода, оптимизация читаемости

**Comment by YuriSilenok** [comment]
И на это у нас есть время сейчас?

**Comment by MariaMakii** [comment]
> И на это у нас есть время сейчас?

Это лучше не откладывать на потом, потому что в той верстке черт ногу сломит, и дальнейшие доработки будут очень затруднительны.

**Comment by YuriSilenok** [comment]
Потом это когда?
Почему вы считаете что рефакторинг верстки как-то упростит жизнь?

**Comment by MariaMakii** [comment]
> Потом это когда? Почему вы считаете что рефакторинг верстки как-то упростит жизнь?

Потом - это после решения какой-либо из основных задач. Не хочу запутывать код еще больше.
Рефакторинг верстки нужен для того, чтобы в дальнейшем эту верстку можно было бы легко читать и дорабатывать. Например, это будет нужно, когда будем делать дизайн.

**Comment by YuriSilenok** [comment]
Такой же вопрос https://github.com/Students-of-the-city-of-Kostroma/tournament-project/issues/29#issuecomment-1011880888 продолжим обсуждение там
