### ISSUE TITLE
Рефакторинг кода для регистрации участников

### ISSUE THREAD

**Issue by MariaMakii** [Students-of-the-city-of-Kostroma/tournament-project#29]

**Comment by YuriSilenok** [comment]
У нас нет других задач, что мы занялись рефакторингом?

**Comment by MariaMakii** [comment]
> У нас нет других задач, что мы занялись рефакторингом?

Если мы сейчас не займемся рефакторингом, то решение следующих задач и поиск ошибок, при их появлении, будут занимать критически много времени и сил

**Comment by YuriSilenok** [comment]
Это каким образом связано?
Разве студия не указывает конкретные строки с ошибкой?

**Comment by YuriSilenok** [comment]
каким образом перенос аргументов ноды помогает отлаживать приложение? и почему вы использовали слово **критически**, у вас была какая-то ситуация?
![image](https://user-images.githubusercontent.com/14871471/148661459-4e9d143b-8d09-47b8-9e84-248ba962b902.png)

**Comment by MariaMakii** [comment]
> Это каким образом связано? Разве студия не указывает конкретные строки с ошибкой?

Я говорю об ошибках в логике, а не о багах, которые приведут к краху приложения.

**Comment by MariaMakii** [comment]
> каким образом перенос аргументов ноды помогает отлаживать приложение? и почему вы использовали слово **критически**, у вас была какая-то ситуация? ![image](https://user-images.githubusercontent.com/14871471/148661459-4e9d143b-8d09-47b8-9e84-248ba962b902.png)

Это улучшение читаемости.
А насчет критичности, да. Например, чтобы решить проблему с неправильным распределением участников с учетом правил, придется пересмотреть всю логику заново, а из-за того, что она может быть запутанной и неочевидной, это займет слишком много времени. Я хочу избежать подобных ситуаций в будущем, поэтому решила пересмотреть код сейчас.

**Comment by YuriSilenok** [comment]
в верстке нет логики, зачем читать код верстки, если проблемы в логике, которой нет в вёрстке? От того, что у вас где-то что-то прочиталось лучше, менять код во всем проекте, плохая практика. Хорошая практика, договориться что бы новых код разрабатывался по каким-то принятым в команде стандартам. Почему перенос атрибутов в ноде является критическим важным я так и не понял.

**Comment by MariaMakii** [comment]
> в верстке нет логики, зачем читать код верстки, если проблемы в логике, которой нет в вёрстке? От того, что у вас где-то что-то прочиталось лучше, менять код во всем проекте, плохая практика. Хорошая практика, договориться что бы новых код разрабатывался по каким-то принятым в команде стандартам. Почему перенос атрибутов в ноде является критическим важным я так и не понял.

Перенос не критически важен, но полезен для улучшения читаемости.

**Comment by YuriSilenok** [comment]
Если это не важно, то зачем тратить на это время? У вас нет других более важных задач? Думаю нужно менять подход в системе постановки задач, вы делаете то, что не нужно.

**Comment by YuriSilenok** [comment]
я не порнимаю как определить когда задача должна быть завершена, выглядит как что-то бесконечное. Что еще нужно сделать, что бы закрыть эту задачу?
