### ISSUE TITLE
Обработка ошибки при попытке внесения в БД турнира с именем, которое уже используется

### ISSUE THREAD

**Issue by AndreyMaraj** [Students-of-the-city-of-Kostroma/tournament-project#31]
При нажатии на кнопку "Сетка" должна обрабатываться ситуация, когда пользователь назвал турнирную сетку именем, которое уже использовано.

**Comment by YuriSilenok** [comment]
Выглядит как баг, если это так, то проонсультируйтесь с Марией Мындрила о то, как правильно его оформлять.

**Comment by MariaMakii** [comment]
@Myndrila Исправлено в версии [v0.4](https://github.com/Students-of-the-city-of-Kostroma/tournament-project/releases/tag/v0.4)

**Comment by Myndrila** [comment]
Баг не воспроизводится в [v0.4](https://github.com/Students-of-the-city-of-Kostroma/tournament-project/releases/tag/v0.4)
