### ISSUE TITLE
Разработать иконку приложения

### ISSUE THREAD

**Issue by YuriSilenok** [Students-of-the-city-of-Kostroma/tournament-project#33]
# [Figma](https://www.figma.com/file/nsLORfGnQlKdc9838aRRs2/Untitled?node-id=516%3A5889)
### Выбранный вариант иконки
![img0](https://user-images.githubusercontent.com/83533847/150509321-99cf6dcd-ef06-419e-96f9-a55e25909504.jpg)

### Предоставленные дизайнером варианты иконки
![img1](https://user-images.githubusercontent.com/83533847/149780454-e8093e45-d334-4cfe-9d15-c196880e5270.jpg)
![img2](https://user-images.githubusercontent.com/83533847/149780504-e39a2c44-903b-4398-9ec7-cba1879d1bec.jpg)
![img3](https://user-images.githubusercontent.com/83533847/149780536-fc29aa68-5266-4eff-bf60-37d91286eacd.png)
![img4](https://user-images.githubusercontent.com/83533847/149780548-a667279f-affc-44e8-85d5-453ec5645621.jpg)
![img5](https://user-images.githubusercontent.com/83533847/149780554-dfb7887d-6dac-4225-a4a9-b0fc537a0624.jpg)
![img6](https://user-images.githubusercontent.com/83533847/149780563-12f2734c-deeb-4e33-9887-7e87eeecd647.jpg)
![img7](https://user-images.githubusercontent.com/83533847/149780571-857b41be-e8f4-484c-b6c1-e24ee7ff7de0.jpg)
![img8](https://user-images.githubusercontent.com/83533847/149780575-19ebe23e-f45f-484d-a75a-309d88863aa2.jpg)

**Comment by ValeriSavvva** [comment]
# [Figma](https://www.figma.com/file/nsLORfGnQlKdc9838aRRs2/Untitled?node-id=516%3A5889)
![img1](https://user-images.githubusercontent.com/83533847/149780454-e8093e45-d334-4cfe-9d15-c196880e5270.jpg)
![img2](https://user-images.githubusercontent.com/83533847/149780504-e39a2c44-903b-4398-9ec7-cba1879d1bec.jpg)
![img3](https://user-images.githubusercontent.com/83533847/149780536-fc29aa68-5266-4eff-bf60-37d91286eacd.png)
![img4](https://user-images.githubusercontent.com/83533847/149780548-a667279f-affc-44e8-85d5-453ec5645621.jpg)
![img5](https://user-images.githubusercontent.com/83533847/149780554-dfb7887d-6dac-4225-a4a9-b0fc537a0624.jpg)
![img6](https://user-images.githubusercontent.com/83533847/149780563-12f2734c-deeb-4e33-9887-7e87eeecd647.jpg)
![img7](https://user-images.githubusercontent.com/83533847/149780571-857b41be-e8f4-484c-b6c1-e24ee7ff7de0.jpg)
![img8](https://user-images.githubusercontent.com/83533847/149780575-19ebe23e-f45f-484d-a75a-309d88863aa2.jpg)

**Comment by YuriSilenok** [comment]
Видимо на митингле будем смотреть иконки?

**Comment by ValeriSavvva** [comment]
> Видимо на митингле будем смотреть иконки?

Не поняла

**Comment by YuriSilenok** [comment]
ну что там, когда определитесь с тем, какая будет иконка?

**Comment by YuriSilenok** [comment]
![image](https://user-images.githubusercontent.com/14871471/150530275-e890040a-1145-4872-9d5f-1fdafc35055b.png)

**Comment by ValeriSavvva** [comment]
# Выбранный вариант иконки!
![Img](https://user-images.githubusercontent.com/83533847/150530464-8437d06c-85ef-4380-8a6b-d28205586b7b.jpg)
