### ISSUE TITLE
Реструктуризация способа хранения категорий и подгрупп

### ISSUE THREAD

**Issue by MariaMakii** [Students-of-the-city-of-Kostroma/tournament-project#34]
Создание классов для категории, группы и подгруппы для оптимизации доступа к этим данным.
Создание методов для доступа к категориям, группам и подгруппам.

**Comment by YuriSilenok** [comment]
А почему в ветке issue-34 исправлялся какой-то баг?

**Comment by YuriSilenok** [comment]
Вы уже замержили метки, задача в итоге решена?

**Comment by YuriSilenok** [comment]
Почему вы делаете задачи которые вас не просили делать?

**Comment by YuriSilenok** [comment]
Почему это вдруг рефакторинг, вы новые сущности реализуете?

**Comment by MariaMakii** [comment]
> А почему в ветке issue-34 исправлялся какой-то баг?

Этот баг был исправлен до этого, но коммит почему-то попал в эту ветку.

**Comment by MariaMakii** [comment]
> Вы уже замержили ветки, в итоге задача решена?

Задача по реструктуризации решена

**Comment by MariaMakii** [comment]
> ы делаете задачи которые вас не просили делать?

Потому что следующие мои задачи - это починка багов. Чтобы починить баг и избежать появления ему подобных я изменяю подход к хранению подгрупп. Это нужно мне для упрощения логики.

**Comment by MariaMakii** [comment]
> Почему это вдруг рефакторинг, вы новые сущности реализуете?

Убрала пометку о рефакторинге.
