### ISSUE TITLE
Выделение категорий с маленьким количеством участников

### ISSUE THREAD

**Issue by MariaMakii** [Students-of-the-city-of-Kostroma/tournament-project#36]
Необходимо выделять цветом кнопку с категорией, в которой количество участников менее 3-х

**Screenshots**
Категория "юношии" на скриншоте выделена как некорректная
![image](https://user-images.githubusercontent.com/67962653/149676006-069a1f3f-e467-4c61-9b72-1cbc8ecda160.png)

**Comment by YuriSilenok** [comment]
Если что-то замержили в дев, выпускайте билд, тестер должен это протыкать.

**Comment by MariaMakii** [comment]
Проблема:
Необходимо для кнопки задать цвет фона и фоновую картинку (с галочкой). 
За это у кнопки отвечает свойство Background и когда я присваиваю ему картинку - исчезает цвет фона и наоборот.
