### ISSUE TITLE
При самом первом открытии приложения в таблице регистрации остаются предыдущие данные 

### ISSUE THREAD

**Issue by Myndrila** [Students-of-the-city-of-Kostroma/tournament-project#41]
**Describe the bug**
При открытии приложения нового релиза в таблице регистрации отображаются предыдущие данные 

**To Reproduce**
1. Скачать приложение
2. Запустить 
3. Клик на начать турнир 

**Expected result**
При первом запуске приложения нового релиза отображается чистая таблица 

**Actual result**
При первом запуске приложения нового релиза отображаются предыдущие данные 

**Screenshots**
![bug_start](https://user-images.githubusercontent.com/81418253/149793898-2cec97bf-d5ba-4d6e-b264-a551db0827d1.jpg)

**Comment by YuriSilenok** [comment]
связная задача #13
