### ISSUE TITLE
Увеличивается Количество бойцов в группе при переходе к формированию групп более одного раза 

### ISSUE THREAD

**Issue by Myndrila** [Students-of-the-city-of-Kostroma/tournament-project#42]
**Describe the bug**
В _количестве бойцов в группе_ увеличивается число участников при переходе от регистрации к формированию групп более одного раза. Происходит дублирование участников

**To Reproduce**
1. Перейти к формированию групп
2. Вернуться к регистрации кликнув на кнопку _регистрация_
3. Снова перейти к формированию групп
4. Посмотреть на количество бойцов в группе в параметрах группы 
5. Для увеличения количества повторить шаги 1-3

**Expected result**
При повторных переходах к формированию групп количество бойцов в группе остается корректным 

**Actual result**
При повторных переходах к формированию групп количество бойцов в группе увеличивается 

**Screenshots**
![kolvo](https://user-images.githubusercontent.com/81418253/149796014-78abcd34-15ad-4f30-a03a-8e7794fa47b5.jpg)

**Comment by MariaMakii** [comment]
@Myndrila Исправлено в версии [v0.4](https://github.com/Students-of-the-city-of-Kostroma/tournament-project/releases/tag/v0.4)

**Comment by Myndrila** [comment]
Баг не воспроизводится в [v0.4](https://github.com/Students-of-the-city-of-Kostroma/tournament-project/releases/tag/v0.4)
