### ISSUE TITLE
Участники не распределяются по подгруппам при правилах: (одноклубников; города; одноклубников и города; не выбрано ни одно правило) в формировании подгрупп

### ISSUE THREAD

**Issue by Myndrila** [Students-of-the-city-of-Kostroma/tournament-project#43]
**Describe the bug**
Участники не распределяются по подгруппам при правилах: (_одноклубников_; _города_; _одноклубников и города_ ; _не выбрано ни одно правило_ )в формировании подгрупп

**To Reproduce**
1. Перейти к формированию групп
2. Выбрать правило города / правило одноклубников / правило города с одноклубниками / не выбирать правило
3. Кликнуть на кнопку _продолжить_

**Expected result**
Участники распределяются по подгруппам в верном количественном соотношении (количество бойцов и количество подгрупп) и соблюдается правило распределения бойцов

**Actual result**
Участники не распределяются по подгруппам при правилах: одноклубников; города; одноклубников и города; не выбрано правило

**Screenshots**
Правило одноклубников: 
![1](https://user-images.githubusercontent.com/81418253/149824801-2ee67105-7e3e-4881-b0f2-1812da464b05.jpg)
Правило одноклубников и города: 
![2](https://user-images.githubusercontent.com/81418253/149824838-6657f58e-bacd-4ba5-a9ba-8315df3e02a3.jpg)
Правило города: 
![3](https://user-images.githubusercontent.com/81418253/149824857-89186033-49a8-4508-af38-851105b2f447.jpg)
Правило не выбрано: 
![nevybran](https://user-images.githubusercontent.com/81418253/149997633-78098e02-bff8-4137-bcc7-5d456b90c086.jpg)

**Comment by MariaMakii** [comment]
@Myndrila Исправлено в версии [v0.4](https://github.com/Students-of-the-city-of-Kostroma/tournament-project/releases/tag/v0.4)

**Comment by Myndrila** [comment]
Баг не воспроизводится в [v0.4](https://github.com/Students-of-the-city-of-Kostroma/tournament-project/releases/tag/v0.4)
