### ISSUE TITLE
Остаётся Категория удалённого участника в группах номинациях 

### ISSUE THREAD

**Issue by Myndrila** [Students-of-the-city-of-Kostroma/tournament-project#44]
**Describe the bug**
Остаётся Категория удалённого участника в группах номинации 

**To Reproduce**
1. Создать участника (-ов) с новой Категорией
2. Перейти к формированию групп
3. Вернуться к регистрации
4. Удалить участника (-ов) с новой Категорией
5. Перейти к формированию групп

**Expected result**
В Группах номинациях _категории_ участников, которые прошли регистрацию

**Actual result**
В Группах номинациях _категории_ участников, которые прошли регистрацию и были удалены до этого    

**Screenshots**

![image](https://user-images.githubusercontent.com/81418253/149901929-4dc0abbd-5b25-4700-8b97-b74d1ca588ca.jpeg)

**Comment by MariaMakii** [comment]
@Myndrila Исправлено в версии [v0.4](https://github.com/Students-of-the-city-of-Kostroma/tournament-project/releases/tag/v0.4)
