### ISSUE TITLE
Превышается количество участников категории в подгруппах при правилах посевных бойцов и города 

### ISSUE THREAD

**Issue by Myndrila** [Students-of-the-city-of-Kostroma/tournament-project#45]
**Describe the bug**
Превышается количество участников в подгруппах при правилах _посевных и города_ 

**To Reproduce**
Steps:
1. Перейти к формированию групп
2. Выбрать правила _посевных бойцов & одноклубников_

**Expected result**
Участники распределяются в верном количественном соотношении(_Пример:_ 13 участников делятся на 3 подгруппы по: 2; 2; 3; 3; 3)

**Actual result**
Участники распределяются: _*Скриншот*_ 13 участников делится на 3 подгруппы: 16; 16 ; 16  = 48, что превышает количество бойцов в категории (13). 

**Screenshots**
![bug_kolvo](https://user-images.githubusercontent.com/81418253/149990937-ff2ed832-e9a9-4785-a33c-c4668a94c344.jpg)

**Comment by MariaMakii** [comment]
@Myndrila Исправлено в версии [v0.4](https://github.com/Students-of-the-city-of-Kostroma/tournament-project/releases/tag/v0.4)

**Comment by Myndrila** [comment]
Баг не воспроизводится в [v0.4](https://github.com/Students-of-the-city-of-Kostroma/tournament-project/releases/tag/v0.4)
