### ISSUE TITLE
Дублируются участники в подгруппах и между подгрупп при правилах посевных бойцов и города

### ISSUE THREAD

**Issue by Myndrila** [Students-of-the-city-of-Kostroma/tournament-project#46]
**Describe the bug**
Дублируются участники в подгруппах и между подгрупп при правилах посевных бойцов и города

**To Reproduce**
Steps:
1. Перейти к формированию групп
2. Выбрать правила _посевных бойцов & города

**Expected result**
Участник в подгруппе и между подгрупп в единственном экземпляре

**Actual result**
Участник дублируется в подгруппе и между подгрупп

**Screenshots**
![bug_double](https://user-images.githubusercontent.com/81418253/149993440-7f63f5a0-1988-438d-9023-5a14ccbab376.jpg)

**Comment by MariaMakii** [comment]
@Myndrila Исправлено в версии [v0.4](https://github.com/Students-of-the-city-of-Kostroma/tournament-project/releases/tag/v0.4)

**Comment by Myndrila** [comment]
Баг не воспроизводится в [v0.4](https://github.com/Students-of-the-city-of-Kostroma/tournament-project/releases/tag/v0.4)
