### ISSUE TITLE
Увеличивается количество бойцов в группе при клике на кнопку продолжить более одного раза

### ISSUE THREAD

**Issue by Myndrila** [Students-of-the-city-of-Kostroma/tournament-project#47]
**Describe the bug**
Увеличивается количество бойцов в группе при клике на кнопку _продолжить_ более одного раза

**To Reproduce**
1. Сформировать подгруппы
2. Кликнуть на кнопку _продолжить_ пару или несколько раз

**Expected result**
Количество бойцов увеличивается после кликов на кнопку _продолжить_ более одного раза 

**Actual result**
Количество бойцов остаётся неизмененным после кликов на кнопку _продолжить_ более одного раза 

**Screenshots**
![prodol](https://user-images.githubusercontent.com/81418253/149997871-763d2b8f-0e4c-4cfa-9982-760e90621ccd.jpg)

**Comment by MariaMakii** [comment]
@Myndrila Исправлено в версии [v0.4](https://github.com/Students-of-the-city-of-Kostroma/tournament-project/releases/tag/v0.4)

**Comment by Myndrila** [comment]
Баг не воспроизводится в [v0.4](https://github.com/Students-of-the-city-of-Kostroma/tournament-project/releases/tag/v0.4)
