### ISSUE TITLE
Прототип окошка с протоколом боя

### ISSUE THREAD

**Issue by YuriSilenok** [Students-of-the-city-of-Kostroma/tournament-project#67]
Окно должно открываться со страницы Турнирная сетка. В окне должны располагаться элементы согласно дизайну.
 - Во всех полях, кроме поля Судья, должны указываться числовые значения.
 - Выподающий список заполняется из окна Судьи
![image](https://user-images.githubusercontent.com/14871471/151842620-e1a82df6-5c50-44e4-9913-4f6d54f9527a.png)
---
Выпустит релиз и отдать в тестирование 12.02.2022

---
Блокирующие задачи:
- #104

**Comment by AndreyMaraj** [comment]
Необходимо переверстать окно под новый макет.

**Comment by YuriSilenok** [comment]
> Необходимо переверстать окно под новый макет.

А где вы берете новый макет, в задача #104 я не нашел информации об этом
